site_name: Math Problems
site_url: https://unclesam13.github.io/Math_Problems_Repo/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          default: true
          build: true
          nav:
            - Home: 'index.md'
            - 'Lecture: Probabilistic Methods':
              - Probabilistic Methods:
                - Basic:
                    - '1. Events & Probability': '4_Metody_probabilistyczne/basic/01_events_and_probability.md'
                    - '2. Combinatorics': '4_Metody_probabilistyczne/basic/02_combinatorics.md'
                    - '3. Probability Distributions': '4_Metody_probabilistyczne/basic/03_probability_distributions.md'
                - 'My Solutions':
                  - 'Solution 1 - Events & Probability': 
                    - 'Task 1 - Coin Tossing': '4_Metody_probabilistyczne/basic/solutions_01_events_and_probability/solution_01.md'
                    - 'Task 2 - Dice Roll': '4_Metody_probabilistyczne/basic/solutions_01_events_and_probability/solution_02.md'
                    - 'Task 3 - Card Draw': '4_Metody_probabilistyczne/basic/solutions_01_events_and_probability/solution_03.md'
                    - 'Task 4 - Weekly Weather Observation': '4_Metody_probabilistyczne/basic/solutions_01_events_and_probability/solution_04.md'
                    - 'Task 5 - Buffon Needle': '4_Metody_probabilistyczne/basic/solutions_01_events_and_probability/solution_05.md'
                    - 'Task 6 - Events and Probabilities in Coin Tossing': '4_Metody_probabilistyczne/basic/solutions_01_events_and_probability/solution_06.md'
                    - 'Task 7 - Events and Probabilities in Die Rolling': '4_Metody_probabilistyczne/basic/solutions_01_events_and_probability/solution_07.md'
                    - 'Task 8 - Events and Probabilities in Card Drawing': '4_Metody_probabilistyczne/basic/solutions_01_events_and_probability/solution_08.md'
                    - 'Task 9 - Events and Probabilities in Weekly Weather Observation': '4_Metody_probabilistyczne/basic/solutions_01_events_and_probability/solution_09.md'
                    - 'Task 10 - Events and Probabilities in Buffon Needle': '4_Metody_probabilistyczne/basic/solutions_01_events_and_probability/solution_10.md'
                  - 'Solution 2 - Combinatorics': 
                    - 'Task 1 - Recognizing Counting Methods': '4_Metody_probabilistyczne/basic/solutions_02_combinatorics/solution_01.md'
                    - 'Task 2 - Permutations': '4_Metody_probabilistyczne/basic/solutions_02_combinatorics/solution_02.md'
                    - 'Task 3 - Permutations with Repeated Elements': '4_Metody_probabilistyczne/basic/solutions_02_combinatorics/solution_03.md'
                    - 'Task 4 - Circular Permutations': '4_Metody_probabilistyczne/basic/solutions_02_combinatorics/solution_04.md'
                    - 'Task 5 - Combinations': '4_Metody_probabilistyczne/basic/solutions_02_combinatorics/solution_05.md'
                    - 'Task 6 - Combinations in Card Problems': '4_Metody_probabilistyczne/basic/solutions_02_combinatorics/solution_06.md'
                    - 'Task 7 - k-Permutations': '4_Metody_probabilistyczne/basic/solutions_02_combinatorics/solution_07.md'
                    - 'Task 8 - Sequences with Repetition': '4_Metody_probabilistyczne/basic/solutions_02_combinatorics/solution_08.md'
                    - 'Task 9 - Digit Restrictions': '4_Metody_probabilistyczne/basic/solutions_02_combinatorics/solution_09.md'
                    - 'Task 10 - Urn Models': '4_Metody_probabilistyczne/basic/solutions_02_combinatorics/solution_10.md'
                    - 'Task 11 - Modeling Outcomes': '4_Metody_probabilistyczne/basic/solutions_02_combinatorics/solution_11.md'
                    - 'Task 12 - Mixed Counting Problem': '4_Metody_probabilistyczne/basic/solutions_02_combinatorics/solution_12.md'
                    - 'Notes - Combinatorics': '4_Metody_probabilistyczne/basic/solutions_02_combinatorics/notes_solutions_02.md'
                    - '4. Discovering Formalism': '4_Metody_probabilistyczne/basic/04_discovery_formalism.md'
                - Advanced:
                    - '1. Events & Probability': '4_Metody_probabilistyczne/advanced/01_events_and_probability.md'
                    - '2. Random Variables': '4_Metody_probabilistyczne/advanced/02_random_variables.md'
                    - '3. Distribution Parameters': '4_Metody_probabilistyczne/advanced/03_distribution_parameters.md'
                    - '4. Selected Distributions': '4_Metody_probabilistyczne/advanced/04_selected_distributions.md'
                    - '5. Limit Theorems': '4_Metody_probabilistyczne/advanced/05_limit_theorems.md'
                    - '6. Basic Statistics': '4_Metody_probabilistyczne/advanced/06_basic_statistics.md'
                    - '7. Estimation': '4_Metody_probabilistyczne/advanced/07_estimation.md'
                    - '8. Hypothesis Testing': '4_Metody_probabilistyczne/advanced/08_hypothesis_testing.md'
                    - '9. Correlation & Regression': '4_Metody_probabilistyczne/advanced/09_correlation_and_regression.md'
                    - '10. Advanced Methods': '4_Metody_probabilistyczne/advanced/10_advanced_methods.md'
                    - '11. Decision Theory': '4_Metody_probabilistyczne/advanced/11_decision_theory.md'
              - Animations:
                - 'Solution 1 - Events & Probability': 
                  - 'Task 1 - Coin Toss': 'en/anim/4_Metody_probalistyczne/coin_toss.html'
                  - 'Task 2 - Dice Roll': 'en/anim/4_Metody_probalistyczne/dice_roll.html'
                  - 'Task 3 - Card Draw': 'en/anim/4_Metody_probalistyczne/card_draw.html'
