site_name: Math Problems
site_url: https://unclesam13.github.io/Math_Problems_Repo/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          default: true
          build: true
          nav:
            - Home: 'index.md'
            - 'Lecture: Mathematics':
              - Algebra:
                - '1. Matrices & Operations': '1_Algebra/01_matrices_and_operations.md'
                - '2. Determinants': '1_Algebra/02_determinants.md'
                - '3. Matrix Inversion': '1_Algebra/03_matrix_inversion.md'
                - '4. Systems of Equations': '1_Algebra/04_systems_of_equations.md'
              - Geometry:
                - '1. Vectors': '2_Geometria/01_vectors.md'
                - '2. Lines': '2_Geometria/02_lines.md'
                - '3. Planes': '2_Geometria/03_planes.md'
                - '4. Line and Plane': '2_Geometria/04_line_and_plane.md'
              - Analysis:
                - '1. Sequence Limits': '3_Analiza/01_sequence_limits.md'
                - '2. Function Limits': '3_Analiza/02_function_limits.md'
                - '3. Derivatives': '3_Analiza/03_derivatives.md'
                - '4. Function Analysis': '3_Analiza/04_function_analysis.md'
                - '5. Integrals': '3_Analiza/05_integrals.md'
                - '6. Calculus Applications': '3_Analiza/06_applications.md'
            - 'Lecture: Probabilistic Methods':
              - Probabilistic Methods:
                - Basic:
                    - '1. Events & Probability': '4_Metody_probabilistyczne/basic/01_events_and_probability.md'
                    - '2. Combinatorics': '4_Metody_probabilistyczne/basic/02_combinatorics.md'
                    - '3. Probability Distributions': '4_Metody_probabilistyczne/basic/03_probability_distributions.md'
                - 'My Solutions':
                  - 'Task 1': 
                    - 'Solution 01 - Task 1 - Coin Tossing': '4_Metody_probabilistyczne/basic/solutions_01_events_and_probability/solution_01.md'
                    - 'Solution 01 - Task 2 - Dice Roll': '4_Metody_probabilistyczne/basic/solutions_01_events_and_probability/solution_02.md'
                    - 'Solution 01 - Task 3 - Card Draw': '4_Metody_probabilistyczne/basic/solutions_01_events_and_probability/solution_03.md'
                    - 'Solution 01 - Task 4 - Weekly Weather Observation': '4_Metody_probabilistyczne/basic/solutions_01_events_and_probability/solution_04.md'
                    - 'Solution 01 - Task 5 - Buffon Needle': '4_Metody_probabilistyczne/basic/solutions_01_events_and_probability/solution_05.md'
                    - 'Solution 01 - Task 6 - Events and Probabilities in Coin Tossing': '4_Metody_probabilistyczne/basic/solutions_01_events_and_probability/solution_06.md'
                    - 'Solution 01 - Task 7 - Events and Probabilities in Die Rolling': '4_Metody_probabilistyczne/basic/solutions_01_events_and_probability/solution_07.md'
                    - 'Solution 01 - Task 8 - Events and Probabilities in Card Drawing': '4_Metody_probabilistyczne/basic/solutions_01_events_and_probability/solution_08.md'
                    - 'Solution 01 - Task 9 - Events and Probabilities in Weekly Weather Observation': '4_Metody_probabilistyczne/basic/solutions_01_events_and_probability/solution_09.md'
                    - 'Solution 01 - Task 10 - Events and Probabilities in Buffon Needle': '4_Metody_probabilistyczne/basic/solutions_01_events_and_probability/solution_10.md'
                - Advanced:
                    - '1. Events & Probability': '4_Metody_probabilistyczne/advanced/01_events_and_probability.md'
                    - '2. Random Variables': '4_Metody_probabilistyczne/advanced/02_random_variables.md'
                    - '3. Distribution Parameters': '4_Metody_probabilistyczne/advanced/03_distribution_parameters.md'
                    - '4. Selected Distributions': '4_Metody_probabilistyczne/advanced/04_selected_distributions.md'
                    - '5. Limit Theorems': '4_Metody_probabilistyczne/advanced/05_limit_theorems.md'
                    - '6. Basic Statistics': '4_Metody_probabilistyczne/advanced/06_basic_statistics.md'
                    - '7. Estimation': '4_Metody_probabilistyczne/advanced/07_estimation.md'
                    - '8. Hypothesis Testing': '4_Metody_probabilistyczne/advanced/08_hypothesis_testing.md'
                    - '9. Correlation & Regression': '4_Metody_probabilistyczne/advanced/09_correlation_and_regression.md'
                    - '10. Advanced Methods': '4_Metody_probabilistyczne/advanced/10_advanced_methods.md'
                    - '11. Decision Theory': '4_Metody_probabilistyczne/advanced/11_decision_theory.md'
              - Animations:
                - 'Solution 1 - Task 1 - Coin Toss': 'en/anim/4_Metody_probalistyczne/coin_toss.html'
                - 'Solution 1 - Task 2 - Dice Roll': 'en/anim/4_Metody_probalistyczne/dice_roll.html'
                - 'Solution 1 - Task 3 - Card Draw': 'en/anim/4_Metody_probalistyczne/card_draw.html'
